**Step 1: Create a Random Tensor of Shape (4, 6)**

We will create a random tensor using TensorFlow.

In [13]:
import tensorflow as tf

# Create a random tensor of shape (4, 6)
tensor = tf.random.uniform(shape=(4, 6), minval=0, maxval=10, dtype=tf.int32)
print("Original Tensor:\n", tensor.numpy())

Original Tensor:
 [[5 1 0 1 5 1]
 [1 2 3 7 6 0]
 [9 2 9 1 3 5]
 [4 9 8 2 5 5]]


**Step 2: Find Its Rank and Shape**

Use TensorFlow functions to determine the rank (number of dimensions) and shape of the tensor.

In [14]:
# Step 2: Find the rank and shape of the tensor
rank = tf.rank(random_tensor)
shape = tf.shape(random_tensor)

print("Rank of the tensor:", rank.numpy())
print("Shape of the tensor:", shape.numpy())

Rank of the tensor: 2
Shape of the tensor: [4 6]


**Step 3: Reshape and Transpose the Tensor**

Reshaped the tensor to (2, 3, 4) and then transposed it to (3, 2, 4).

In [11]:
# Step 3: Reshape the tensor to (2, 3, 4)
reshaped_tensor = tf.reshape(tensor, (2, 3, 4))
print("Reshaped Tensor (2, 3, 4):\n", reshaped_tensor.numpy())

# Transpose the reshaped tensor to (3, 2, 4)
transposed_tensor = tf.transpose(reshaped_tensor, perm=[1, 0, 2])
print("Transposed Tensor (3, 2, 4):\n", transposed_tensor.numpy())

# Print rank and shape after reshaping and transposing
print("Rank after reshaping and transposing:", tf.rank(transposed_tensor).numpy())
print("Shape after reshaping and transposing:", transposed_tensor.shape)

Reshaped Tensor (2, 3, 4):
 [[[9 9 5 0]
  [0 5 2 7]
  [8 1 3 3]]

 [[7 1 7 3]
  [3 0 0 9]
  [4 0 1 1]]]
Transposed Tensor (3, 2, 4):
 [[[9 9 5 0]
  [7 1 7 3]]

 [[0 5 2 7]
  [3 0 0 9]]

 [[8 1 3 3]
  [4 0 1 1]]]
Rank after reshaping and transposing: 3
Shape after reshaping and transposing: (3, 2, 4)


**Step 4: Broadcast a Smaller Tensor and Add**

Created a smaller tensor of shape (1, 4) and broadcast it to match the shape of the larger tensor (3, 2, 4). Then, perform element-wise addition.

In [12]:
# Step 4: Broadcasting and Adding Tensors
# Create a smaller tensor of shape (1, 4)
small_tensor = tf.constant([[1, 2, 3, 4]], dtype=tf.int32)

# Broadcast the smaller tensor to match the shape of the larger tensor (3, 2, 4)
broadcasted_tensor = tf.broadcast_to(small_tensor, transposed_tensor.shape)
print("Broadcasted Tensor (3, 2, 4):\n", broadcasted_tensor.numpy())

# Add the broadcasted tensor to the transposed tensor
result_tensor = transposed_tensor + broadcasted_tensor
print("Result Tensor after Addition:\n", result_tensor.numpy())

Broadcasted Tensor (3, 2, 4):
 [[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]
Result Tensor after Addition:
 [[[10 11  8  4]
  [ 8  3 10  7]]

 [[ 1  7  5 11]
  [ 4  2  3 13]]

 [[ 9  3  6  7]
  [ 5  2  4  5]]]


**Step 5: Explain Broadcasting in TensorFlow**

Broadcasting is a mechanism in TensorFlow that allows operations between tensors of different shapes by automatically expanding the smaller tensor to match the shape of the larger tensor. The rules for broadcasting are:

**Align dimensions:** Start from the rightmost dimension and move left.

**Expand dimensions:** If one tensor has a size of 1 in a dimension, it is stretched to match the size of the other tensor in that dimension.

**Incompatible shapes:** If the dimensions are not equal and neither is 1, broadcasting fails.

**In this task:**

The smaller tensor (1, 4) is broadcasted to (3, 2, 4) by repeating its values along the first and second dimensions
